---

image_topic: '/head_camera/rgb/image_raw'
camera_info_topic: '/head_camera/rgb/camera_info'
frame_id: '/head_camera_rgb_optical_frame'
pc_topic: '/head_camera/depth_registered/points'
               
grid0_size_x: 6
grid0_size_y: 4
board_type: 'chess'
rect0_size_x: 0.035
rect0_size_y: -0.035
type0: '/world_raw'
~use_simple_tf: true
message_throttle: 1

